import {
  ShoppingCart,
  Car,
  Home,
  Zap,
  Clapperboard,
  Utensils,
  Heart,
  Briefcase,
  GraduationCap,
  Gift,
  Landmark,
  TrendingUp,
  type LucideIcon,
  CircleDollarSign,
  Smartphone,
  Dog,
  Cat,
  Receipt,
  Shirt,
  Plane,
  HeartPulse,
} from 'lucide-react';
import type { Category } from './types';

export const categoryIcons: { [key: string]: LucideIcon } = {
  'ShoppingCart': ShoppingCart,
  'Car': Car,
  'Home': Home,
  'Zap': Zap,
  'Clapperboard': Clapperboard,
  'Utensils': Utensils,
  'Heart': Heart,
  'Briefcase': Briefcase,
  'GraduationCap': GraduationCap,
  'Gift': Gift,
  'Landmark': Landmark,
  'TrendingUp': TrendingUp,
  'CircleDollarSign': CircleDollarSign,
  'Smartphone': Smartphone,
  'Dog': Dog,
  'Cat': Cat,
  'Receipt': Receipt,
  'Shirt': Shirt,
  'Plane': Plane,
  'HeartPulse': HeartPulse,
};

export const defaultCategories: Omit<Category, 'id'| 'familyMemberId'>[] = [
  { name: 'Продукти', icon: 'ShoppingCart', type: 'expense', order: 0 },
  { name: 'Транспорт', icon: 'Car', type: 'expense', order: 1 },
  { name: 'Житло', icon: 'Home', type: 'expense', order: 2 },
  { name: 'Комунальні послуги', icon: 'Zap', type: 'expense', order: 3 },
  { name: 'Моб. зв\'язок', icon: 'Smartphone', type: 'expense', order: 4 },
  { name: 'Одяг', icon: 'Shirt', type: 'expense', order: 5 },
  { name: 'Здоров\'я та спорт', icon: 'HeartPulse', type: 'expense', order: 6 },
  { name: 'Розваги', icon: 'Clapperboard', type: 'expense', order: 7 },
  { name: 'Харчування поза домом', icon: 'Utensils', type: 'expense', order: 8 },
  { name: 'Освіта', icon: 'GraduationCap', type: 'expense', order: 9 },
  { name: 'Подорожі', icon: 'Plane', type: 'expense', order: 10 },
  { name: 'Подарунки', icon: 'Gift', type: 'expense', order: 11 },
  { name: 'Домашні улюбленці', icon: 'Dog', type: 'expense', order: 12 },
  { name: 'Інше', icon: 'CircleDollarSign', type: 'expense', order: 13 },
  { name: 'Зарплата', icon: 'Landmark', type: 'income', order: 14 },
  { name: 'Інвестиції', icon: 'TrendingUp', type: 'income', order: 15 },
  { name: 'Подарунки (дохід)', icon: 'Gift', type: 'income', order: 16 },
  { name: 'Інше (дохід)', icon: 'CircleDollarSign', type: 'income', order: 17 },
];
